import React from "react";
import OrderListProps from "./orderListType";
import { MainLoader } from "../Common";
import { orderHeaderModel } from "../../../Interfaces";
import { useNavigate } from "react-router-dom";
import { getStatusColor } from "../../../Helper";

function OrderList({ isLoading, orderData }: OrderListProps) {
  const navigate = useNavigate();

  return (
    <>
      {/* if the data is loading, display main */}
      {isLoading && <MainLoader />}
      {/* if the data is not loading, display the orders */}
      {!isLoading && (
        <div className="table px-5">
          <div className="p-2">
            <div className="row border text-center">
              <div className="col-1" style={styles.column}>
                ID
              </div>
              <div className="col-1" style={styles.column}>
                Name
              </div>
              <div className="col-1" style={styles.column}>
                Phone
              </div>
              <div className="col-2" style={styles.column}>
                Address
              </div>
              <div className="col-1" style={styles.column}>
                Total
              </div>
              <div className="col-1" style={styles.column}>
                Items
              </div>
              <div className="col-2" style={styles.column}>
                Date
              </div>
              <div className="col-1" style={styles.column}>
                Status
              </div>
              <div className="col-2"></div>
            </div>

            {orderData.map((orderItem: orderHeaderModel) => {
              const badgecolor = getStatusColor(orderItem.status!);

              return (
                <div
                  className="row border align-items-center justify-content-center text-center"
                  key={orderItem.orderHeaderId}
                >
                  <div className="col-1">{orderItem.orderHeaderId}</div>
                  <div className="col-1">{orderItem.pickupName}</div>
                  <div className="col-1">{orderItem.pickupPhoneNumber}</div>
                  <div className="col-2">{orderItem.pickupAddress}</div>
                  <div className="col-1">
                    ${orderItem.orderTotal!.toFixed(2)}
                  </div>
                  <div className="col-1">{orderItem.totalItems}</div>
                  <div className="col-2">
                    {new Date(orderItem.orderDate!).toLocaleDateString()}
                  </div>

                  <div className="col-1 d-flex align-items-center justify-content-center">
                    <span className={`badge bg-${badgecolor}`}>
                      {orderItem.status}
                    </span>
                  </div>

                  <div className="col-2">
                    <button
                      className="btn btn-success"
                      // order Details generated by order id
                      onClick={() =>
                        navigate(
                          "/order/orderDetails/" + orderItem.orderHeaderId
                        )
                      }
                    >
                      Details
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </>
  );
}

const styles = {
  column: {
    fontWeight: "bold",
    color: "black",
  },
};

export default OrderList;
